apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-api
  template:
    metadata:
      labels:
        app: bird-api
    spec:
      containers:
      - name: bird-api
        image: birdapp-bird-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4201
        env:
        - name: BIRD_IMAGE_API
          value: "http://bird-image-api:4200"
---
apiVersion: v1
kind: Service
metadata:
  name: bird-api
spec:
  type: NodePort
  ports:
  - port: 4201
    targetPort: 4201
    nodePort: 30001
  selector:
    app: bird-api
