apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-image-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-image-api
  template:
    metadata:
      labels:
        app: bird-image-api
    spec:
      containers:
      - name: bird-image-api
        image: birdapp-bird-image-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: bird-image-api
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 30000
  selector:
    app: bird-image-api
