apiVersion: v1
kind: Service
metadata:
  name: bird-api
spec:
  type: NodePort
  ports:
  - port: 4201
    targetPort: 4201
    nodePort: 30001
  selector:
    app: bird-api
---
apiVersion: v1
kind: Service
metadata:
  name: bird-image-api
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 30000
  selector:
    app: bird-image-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: frontend
