services:
  bird-api:
    image: birdapp-bird-api:latest
    build:
      context: ./bird
    ports:
      - "4201:4201"
    depends_on: 
      - bird-image-api
    environment:
      - BIRD_IMAGE_API=http://bird-image-api:4200
    networks:
      - bird-app-net
  bird-image-api:
    image: birdapp-bird-image-api:latest
    build:
      context: ./birdImage
    ports:
      - "4200:4200"
    networks:
      - bird-app-net
  frontend:
    image: birdapp-frontend:latest
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on: 
      - bird-image-api
      - bird-api
    networks:
      - bird-app-net
 
networks:
  bird-app-net:
